### ISSUE TITLE
Crash on loadup 

### ISSUE THREAD

**Issue by chudders1231** [fzzyhmstrs/tns#3]
I updated trident's n' stuff to `0.2.0+1.20.1` , fzzy config to `0.4.3+1.20.1` and fzzy core to `0.5.1+1.20.` and getting the following error.

What is it that could be causing this if everything is updated?

`4/09/2024 17:11:38 pm] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tridents_n_stuff' at 'me.fzzyhmstrs.tridents_n_stuff.TNS'!
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[24/09/2024 17:11:38 pm] 	at net.minecraft.class_310.<init>(class_310.java:458)
[24/09/2024 17:11:38 pm] 	at net.minecraft.client.main.Main.main(Main.java:211)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[24/09/2024 17:11:38 pm] Caused by: java.lang.NoSuchMethodError: 'net.peanuuutz.tomlkt.TomlLiteral net.peanuuutz.tomlkt.TomlElementKt.TomlLiteral(int)'
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.serializeToToml$fzzy_config(ConfigApiImpl.kt:281)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.serializeConfig$fzzy_config(ConfigApiImpl.kt:343)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.serializeConfig$fzzy_config$default(ConfigApiImpl.kt:342)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.readOrCreateAndValidate$fzzy_config(ConfigApiImpl.kt:151)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.readOrCreateAndValidate$fzzy_config(ConfigApiImpl.kt:224)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.registerAndLoadBoth(ConfigApiImpl.kt:112)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.impl.ConfigApiImpl.registerAndLoadConfig$fzzy_config(ConfigApiImpl.kt:106)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.api.ConfigApi.registerAndLoadConfig(ConfigApi.kt:104)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.fzzy_config.api.ConfigApi.registerAndLoadConfig$default(ConfigApi.kt:101)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.tridents_n_stuff.config.TnsConfig.<clinit>(TnsConfig.kt:89)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.tridents_n_stuff.registry.RegisterItem.<clinit>(RegisterItem.kt:25)
[24/09/2024 17:11:38 pm] 	at me.fzzyhmstrs.tridents_n_stuff.TNS.onInitialize(tridents_n_stuff.kt:25)
[24/09/2024 17:11:38 pm] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
[24/09/2024 17:11:38 pm] 	... 6 more`

**Comment by fzzyhmstrs** [comment]
Can you please provide the full log. I have a suspicion, but need the full log to know for sure

**Comment by Akoto090** [comment]
[crash-2024-10-06_14.09.26-client.txt](https://github.com/user-attachments/files/17269307/crash-2024-10-06_14.09.26-client.txt)
[latest.log](https://github.com/user-attachments/files/17269308/latest.log)

here got the same issue in one pack

**Comment by fzzyhmstrs** [comment]
Thank you. As I suspected, Bypass Anvil Restrictions is adding an outdated version of TomlKt, which is incompatible with the version Fzzy Config uses
![image](https://github.com/user-attachments/assets/dc35516e-f467-4802-87af-06103c0f9c8a)

I've already raised an issue with them, but no response so far. Basically, at this point, Bypass Anvil Restrictions is incompatible with TnS at this time

https://github.com/AmibeSkyfy16/BypassAnvilRestriction/issues/1

**Comment by Akoto090** [comment]
Thank you, will report this to the modpack!
